### ISSUE TITLE
跑起来fuse点云需要多大的内存

### ISSUE THREAD

**Issue by LeoDuhz** [zhulf0804/3D-PointCloud#3]
您好，我现在在跑由50张RGBD图片生成点云的代码，但是我的16GB内存电脑完全带不动，想知道您用多大的内存以及对应的CPU配置能跑起来呢

**Comment by zhulf0804** [comment]
如果点云的points数量比较大, 可以考虑下采样处理, 来支撑你的内存和CPU.
我用的是8 或 32G内存, 用8G内存基本可以处理大多数的任务了.
