### ISSUE TITLE
Request to add paper

### ISSUE THREAD

**Issue by ldkong1205** [zhulf0804/3D-PointCloud#5]
Thank you for meticulously maintaining this repository!

Could you add our recent work on LiDAR segmentation? We built the first benchmark for unsupervised domain adaptation (UDA) in LiDAR segmentation (range-view). We also proposed a new UDA algorithm which has achieved promising results.

- **Title:** ConDA: Unsupervised Domain Adaptation for LiDAR Segmentation via Regularized Domain Concatenation
- **Link**: https://arxiv.org/abs/2111.15242
- **Authors:** Lingdong Kong, Niamul Quader, Venice Erin Liong, Hanwang Zhang
- **Affiliations:** Nanyang Technological University, Motional
- **Tags:** `seg`, `uda`, `av`, `lidar`

**Comment by zhulf0804** [comment]
Nice and thank you for your proposal. The paper [ConDA](https://arxiv.org/abs/2111.15242) is added.
